version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: blog-cms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_cms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: blog-cms-api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/blog_cms
      NODE_ENV: production
      PORT: 3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run prisma:migrate:prod && npm start"

volumes:
  postgres_data: